sudo: required

language: generic

cache:
  directories:
    - ~/.npm
    - ~/.cache

services:
  - docker

install:
  - cd ui
  - docker pull logitron1/dungeon-pack-ui:ci
  - docker build -f Dockerfile.ci -t dungeon-pack-ui --cache-from logitron1/dungeon-pack-ui:ci .

script:
  - docker run dungeon-pack-ui npm run test:unit

before_deploy:
  - cd ..

deploy:
  provider: script
  script: bash deploy
  on:
    branch: master