version: '3.6'
services:
  ui:
    build: ./ui
    container_name: dungeon-pack-ui
    stdin_open: true
    tty: true
    command: npm run serve

    volumes:
      - ./ui:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development

    ports:
      - '8080:8080'